name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: pwd

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Add package-lock.json Changes
        working-directory: api
        run: git add package-lock.json

      - name: Run Tests
        working-directory: api
        run: npm run test
