name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Check for Changes
        run: |
          git diff api/package.json --exit-code || echo "Changes found"
          git diff api/package-lock.json --exit-code || echo "Changes found"

      - name: Check for package.json Changes
        id: check_changes
        run: |
          if [ -n "$(git diff -- api/package.json)" ] && [ -z "$(git diff -- api/package-lock.json)" ]; then
            echo "Changes found in package.json but not in package-lock.json"
            exit 78
          fi

      - name: Commit and Push package-lock.json Changes
        if: steps.check_changes.outcome == 'success'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"
          git stash && git pull origin ${GITHUB_HEAD_REF} --rebase
          git stash pop && git commit -am "Update package-lock.json" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_HEAD_REF}

      - name: Build
        working-directory: api
        run: |
          npm run build
          npm run clean

      - name: Lint
        working-directory: api
        run: npm run lint

      - name: Run Tests
        working-directory: api
        run: npm run test
