name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: |
          pwd
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Pull Changes
        run: git pull origin ${GITHUB_HEAD_REF} --rebase

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Build ts
        working-directory: api
        run: |
          npm run build
          npm run clean

      - name: Run Tests
        working-directory: api
        run: npm run test

  pr-lock-file-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check for Changes
        id: check_changes
        run: git diff --exit-code || echo "Changes found"

      - name: Commit and Push package-lock.json Changes
        if: check_changes.result == 'Changes found'
        run: |
          git commit -am "Update package-lock.json" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_HEAD_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
