name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: pwd

      - name: Install Dependencies
        working-directory: api
        run: yarn install

      - name: Run Tests
        working-directory: api
        run: yarn test
