name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"
          echo "git configured"
          git diff
          echo "diff done"
          git diff --name-only
          echo "grep done"

      - name: Check for changes in package.json
        id: check_package_json
        run: |
          if git diff --name-only HEAD | grep 'package\.json'; then
            echo "Changes detected in package.json"
            echo "::set-output name=package_changes::true"
          else
            echo "No changes in package.json"
            echo "::set-output name=package_changes::false"
          fi

      - name: Check for changes in package-lock.json
        id: check_package_lock_json
        if: steps.check_package_json.outputs.package_changes == 'true'
        run: |
          if git diff --name-only HEAD | grep 'package-lock\.json'; then
            echo "Changes detected in package-lock.json"
            echo "::set-output name=package_lock_changes::true"
          else
            echo "No changes in package-lock.json"
            echo "::set-output name=package_lock_changes::false"
          fi

      - name: Fail if changes detected
        if: steps.check_package_json.outputs.package_changes == 'true' || steps.check_package_lock_json.outputs.package_lock_changes == 'true'
        run: exit 1

      - name: Install Dependencies
        working-directory: api
        run: npm install

      # - name: Commit and Push package-lock.json Changes
      #   run: |
      #     git config --global user.email "github-actions@github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git stash && git pull origin ${GITHUB_HEAD_REF} --rebase
      #     git stash pop && git commit -am "Update package-lock.json" || echo "No changes to commit"
      #     git push origin HEAD:${GITHUB_HEAD_REF}

      - name: Build
        working-directory: api
        run: |
          npm run build
          npm run clean

      - name: Lint
        working-directory: api
        run: npm run lint

      - name: Run Tests
        working-directory: api
        run: npm run test
