name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: | 
          pwd
          git config --global user.name 'Felipe Silveira'
          git config --global user.email '"${GITHUB_ACTOR}"@users.noreply.github.com'
          git config --list

      - name: Pull Changes
        run: git pull origin ${GITHUB_HEAD_REF} --rebase

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Commit package-lock.json Changes
        run: git commit -am "Update package-lock.json" || echo "No changes to commit"

      - name: Push Changes
        run: git push origin HEAD:${GITHUB_HEAD_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
      - name: Run Tests
        working-directory: api
        run: npm run test
