name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Check for Changes
        id: check_changes
        run: git diff --exit-code || echo "Changes found" || true

      - name: debug
        run: |
          echo "${{ steps.check_changes.outputs.result }}" 1
          echo "${{ steps.check_changes.outputs }}" 2
          echo "${{ steps.check_changes.outputs.result == 'Changes found' }}" 4
          echo "${{ steps.check_changes.outputs.result }}" 5

      - name: Commit and Push package-lock.json Changes
        if: "${{ steps.check_changes.outputs.result == 'Changes found' }}"
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"
          git stash && git pull origin ${GITHUB_HEAD_REF} --rebase
          git stash pop && git commit -am "Update package-lock.json" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_HEAD_REF}

      - name: Build
        working-directory: api
        run: |
          npm run build
          npm run clean

      - name: Lint
        working-directory: api
        run: npm run lint

      - name: Run Tests
        working-directory: api
        run: npm run test
